### ISSUE TITLE
기능요청

### ISSUE THREAD

**Issue by opencookie** [kimsama/Unity-GoogleData#1]
안녕하세요?
유용하게 잘 사용하고 있습니다. 먼저 감사를^^

이런 기능이 있으면 좋을것 같습니다.

1.
지금은 임포트시에 데이터형을 일일이 버튼으로 선택하도록 되어 있는데, 첫번째줄에 데이터 형을 기입하면 자동으로 선택되도록 하면 어떨까요? 다음 문서의 4번 항목처럼요.
https://easyggsoft.files.wordpress.com/2014/08/docspin_korean.pdf

2.
만들어진 스크립트의 함수명의 대소문자가 구글스프레드시트에 기입한 그대로 유지되면 좋겠네요.
지금은 첫번째 문자외엔 다 소문자로 변해버려서 저처럼 함수명을 파스칼 케이스로 사용하는 사람에겐 맞지 않네요.

**Comment by kimsama** [comment]
안녕하세요, 

이슈는 Unity-GoogleData 페이지에 남겨 주셨는데, 질문 내용을 보니 아마도 Unity-QuickSheet을 사용하고 계신듯 합니다. 

1
데이터형을 버튼으로 선택하는 방식은 QuickSheet에 추가된 기능입니다. GoogleData 코드를 작성할 때에는 첨부한 문서의 4번 항목과 유사하게 두 번째 행에 타입을 기술하는 방법과 첫 번째 행의 header-column에 HP:int와 같이 콜론으로 타입을 기입하는 방법의 두 가지를 모두 테스트해 보긴 했습니다. 이 기능을 뺀 이유는 아래의 몇 가지 이유 때문입니다. 

1) 기존에 작성된 스프레드시트를 수정 없이 사용할 수 있을 것.
2) 스프레드시트를 작성은 대부분 프로그래머가 아닌 이유로 가능한 특별한 규칙을 만들지 말 것. 

사실 엑셀과 달리 Google Spreadsheet의 경우 Google SDK에서 규정하는 몇 가지 규칙이 있습니다. 첫 번째 워크시트(worksheet)는 사용하지 않는다던가, 첫 번째 행은 반드시 헤더컬럼으로 값을 기입하지 않는다 등이 여기에 해당합니다. 때문에 더욱이 복잡한 제 3, 제 4의 규칙을 가급적 넣지 않도록 하는 것이 좋다고 판단했습니다. 

3) 코드에 2)의 이유로 예외의 코드를 배제하기 위함. 

혹 진행 중이신 프로젝트에서 편의를 위해서 말씀하신 바와 같은 기능이 필요한 경우에는 에디터 스크립트쪽의 코드를 수정해서 처리하면 어렵지 않게 구현이 가능해 보입니다. 

다만, 현재로서는 해당 기능의 추가는 고려하지 않고 있습니다. 

2 
Unity-GoogleData 의 경우 꽤 오래 전에, 대략 Unity 3.x 버전에서 시작한 것으로 기억합니다. 

임포트한 데이터값들을 보여주지 않아도 되긴 합니다만, 변경 여부나 변경 사항의 유효성을 실행 전에 바로 확인할 수 있도록 하는 것이 아무래도 기획자와 같은 프로그래머가 아닌 작업자들의 실수를 방지하는데 중요하다고 생각해서 관련한 처리를 reflection을 이용해서 처리했습니다. 

앞에서 설명했듯이 이 처리가 4.x의 PropertyDrawer 등이 나오기 전에 구현된 부분이라 귀차니즘으로 여지껏 해당 코드를 그대로 사용하면서 부득이 멤버 변수와 프로퍼티(Reflection으로 Inspector 뷰에 컨트롤을 그릴 때 사용) 양쪽이 모두 필요하고 변수 이름도 소문자로 변경하는 등의 처리가 필요했던 것으로 기억이 나네요. 

QuickSheet에서는 이 부분의 개선을 위해서 VFX 라이브러리를 사용해서 ScriptableObject의 내용이 Inspector 뷰에 Reflection되도록 처리 하려고 생각 중에 있습니다. QuickSheet-VFX라는 브랜치 중 하나가 바로 이 작업을 위한 것인데 요즘 시간이 나지 않아서 작업에는 시간이 좀 걸릴 듯 합니다. 

이름의 명명 방식은 CamelCase 방식이 될 듯합니다. (사실 처음에 이 부분에 처리도 코드에 포함이 되어 있었는데 Insprector 뷰 처리 작업하면서 삭제되고 코드만 남아 있는 상태입니다. 해당 코드는 아래에서 확인할 수 있습니다. 
https://github.com/kimsama/Unity-GoogleData/blob/master/Assets/Script/GDataPlugin/Editor/BaseEditor.cs )

피드백 감사합니다!  그리고, *도 하나 부탁드려요. ^^

**Comment by opencookie** [comment]
답이 늦었습니다.^^
Unity-QuickSheet에 대한 질문이었는데 Unity-GoogleData에 질문을 남겼네요...-_-;

어떤 이유로 이렇게 구현하였는지 상세히 설명해 주셔서 감사합니다.
말씀하신대로 제가 수정해서 사용해야 겠네요.

그리고, 스타는 둘 다 클릭했습니다.^^
